### ISSUE TITLE
Project name

### ISSUE THREAD

**Issue by maciejhirsz** [HoneyBadger-rust/HoneyBadger#5]
CC @cmtt 

~~I've been thinking about coming with a name that isn't already taken on npm but also doesn't deviate from the badger-ness. One option I got, which sounds kinda cute and should be easy to remember is `badgeroo`~~. 

Edit: we now have access to [ratel](https://en.wikipedia.org/wiki/Ratel) [on npm](https://www.npmjs.com/package/ratel) :).

The github organization can be then changed to:

ratel-rust / ratel-cli -> `ratel` on npm
ratel-rust / ratel-core -> `ratel` on crates.io

Sidenote: project logo could be a yellow JS-esque square with a head profile (plain black + white) of a honey badger in the bottom right corner.

**Comment by cmtt** [comment]
Great news! 
I like that _ratel_ has fewer characters than _HoneyBadger_ and _badgero_.
The best thing is that we can publish on both platforms without conflicting packages.

**Comment by maciejhirsz** [comment]
Ok, I think it's pretty safe to make a run for it :)
